# Generated by Django 5.2.5 on 2025-08-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('ENG', 'Engineering'), ('MKT', 'Marketing'), ('FIN', 'Finance'), ('SALES', 'Sales')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_joined', models.DateField()),
            ],
        ),
    ]
